server {
    listen 80;
    server_name hyperdx.testifypro.uz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hyperdx.testifypro.uz;

    include /etc/nginx/snippets/ssl-params.conf;

    # HyperDX UI
    location / {
        proxy_pass http://127.0.0.1:8080;
        include /etc/nginx/conf.d/proxy-params.conf;
    }

    # HyperDX API
    location /api/ {
        proxy_pass http://127.0.0.1:8000/api/;
        include /etc/nginx/conf.d/proxy-params.conf;
    }
}
