server {
    listen 80;
    server_name taccount.local.testifypro.uz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name taccount.local.testifypro.uz;

    include /etc/nginx/snippets/ssl-params-local.conf;

    location / {
        proxy_pass http://127.0.0.1:5001;
        include /etc/nginx/conf.d/proxy-params.conf;
    }
}
